<?php
$t = __FILE__;
$t = pathinfo($t);
$t = $t[filename];
$pid = $t;

$next_enable = 1;
$next = "/9";
$prev = "/1";
?>

<div class="container">
    <div class="row justify-content-center align-items-center">

<!--  ----------------step 1------------------------------ -->
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4  col-centered text-center">
            <div class=pay>
                <div class=title>
                    RESULTS
                </div>

		<div class=info>
		A simple as <b>Pimper</b>
		</div>
		<div class=msg><span id=msg_txt>&nbsp;</span></div>

<div class=about>

<b>Coming soon</b>
<br>- rewrite frontend as React app including web2 and web3 benefits
<br>- Sending a transaction via Metamask and other compatible web3 wallets for branding NFTs that are generated by passwords
<br>- fiat payments directly from the page with one-time wallets
<br>- transaction history support
<br>- add/set detailed information on NFT
<br>- viewing detailed information on tickets purchased by password and send them to any wallet
<br>
<br><b>Benefits</b>
<br>The app could be used for 2 types of users:
<br>1) Who has a wallet: in this case, visitors pay for an NFT buy FIAT and receive it to the wallet address
<br>2) Who doesn't have any wallet: after payment NFT stores in the smart contract. Only buyer has access to it and can send it to any wallet address using a password generated during the purchase
<br><br>
<p>The ticket seller transparently receives payment for his goods, while the commission for transactions is transparent to the final
user is credited to the Pimper platform through the use of a special smart contract and can be personalized for each individual seller

<p>The project was made as a real business case within the EthWarszaw hackathon and can be used to sell tickets for the following events

<p>Pimper solution is ready to be extended as it fully meets the requirements of the payments regulator.

</div>
            </div>
<?php
include "arrow.php";

?>
        </div>
<!-- ------------------------------------------------------ -->

    </div>
</div>
